version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 2.2
      nodejs: 10
    commands:
      - npm i -g aws-cdk

  pre_build:
    commands:
      - dotnet restore
      - dotnet test -c Release

  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release
      - cdk synth Api -o dist

artifacts:
  files:
    - dist/*
